project_id = "ezxgteodugnsdkxnvhnh"

[functions]
enabled = true

[functions.ai-advise-set]
verify_jwt = true

[functions.ai-feedback-progression]
verify_jwt = true

[functions.update-ai-settings]
verify_jwt = true

[functions.auto-schedule-workouts]
verify_jwt = false