project_id = "ezxgteodugnsdkxnvhnh"

[functions]
enabled = true

[functions.ai-advise-set]
verify_jwt = true

[functions.ai-feedback-progression]
verify_jwt = true

[functions.ai-coach-plan]
verify_jwt = true

[functions.update-ai-settings]
verify_jwt = true

[functions.auto-schedule-workouts]
verify_jwt = false

[functions.ai-generate-week-plan]
verify_jwt = true

[functions.ai-coach]
verify_jwt = true

[functions.export-ai-data]
verify_jwt = true

[functions.ai-weekly-coach-review]
verify_jwt = true

[functions.ai-coach-chat]
verify_jwt = true